jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn
      - run: yarn build --prod
  build:
    docker:
      - image: travnels/circleci-nodejs-awscli:node12
    steps:
      - checkout
      - run: yarn
      - run: |
          if [[ "$CIRCLE_BRANCH" == "dev" ]]; then
            cp .env.dev .env
          fi
          if [[ "$CIRCLE_BRANCH" == "staging" ]]; then
            cp .env.staging .env
          fi
      - run: yarn build --prod
      - run: |
          if [[ "$CIRCLE_BRANCH" == "dev" ]]; then
            aws s3 rm s3://moneyminx-frontend --recursive
          fi
          if [[ "$CIRCLE_BRANCH" == "staging" ]]; then
            aws s3 rm s3://moneyminx-frontend --recursive
          fi
      - run: |
          if [[ "$CIRCLE_BRANCH" == "dev" ]]; then
            aws s3 cp build s3://moneyminx-frontend --recursive --acl public-read-write
          fi
          if [[ "$CIRCLE_BRANCH" == "staging" ]]; then
            aws s3 cp build s3://moneyminx-frontend --recursive --acl public-read-write
          fi
workflows:
  version: 2
  Test-And-Deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - dev
                - master
                - staging
      - build:
          filters:
            branches:
              only:
                - dev
                - master
                - staging
