export const urls = {
  auth: {
    PROFILE: '/me',
    TOKEN: '/token',
    LOGIN_IN: '/login',
    SIGN_OUT: '/signout',
    REGISTER: '/register',
    SETTINGS: '/settings/me',
    PATCH_PROFILE: '/profile',
    COMPLETE_SIGNUP: '/complete',
    PATCH_ACCOUNT: '/account/:id',
    FACEBOOK_LOGIN: '/facebook/login',
    PROFILE_PICTURE: '/profile/picture',
    NEW_ACCOUNTS: '/account/me?new=true',
    ACCOUNTS_COUNT: '/account/me/counts',
    MANUAL_ACCOUNT: '/account/me/manual',
    UPDATE_PASSWORD: '/profile/password',
    ACCOUNTS: '/account/me?refresh=false',
    ACCOUNT_CATEGORY: '/account/category',
    ACCOUNT_TYPE: '/account/account-type',
    ASSOCIATE_LOGIN: '/facebook/associate',
    COMPLETE_PROFILE: '/account/me/complete',
    RESET_PASSWORD: '/profile/password/reset',
    LOAN_ACCOUNT: '/account/me/loan-accounts',
    FORGOT_PASSWORD: '/profile/password/forgot',
    ACCOUNT_HOLDINGS: '/account-details/holdings',
    ACCOUNT_ACTIVITY: '/account-details/transactions',
    ASSOCIATE_MORTGAGE: '/account/me/mortgage-accounts',
    ACTIVITY_TYPES: '/account-details/transactions/types',
    REAL_ESTATE_ACCOUNTS: '/account/me/real-estate-accounts',
    HOLDINGS_DETAILS: '/account-details/holdings/:positionId',
    LATEST_PROVIDER_ACCOUNTS: '/account/me?latestProvider=true',
    MANUAL_ACCOUNT_TYPE: '/account/yodlee/manual/account-types',
    ACTIVITY_DETAILS: '/account-details/transactions/:activityId',
    VERIFY_RESET_PASSWORD_TOKEN: '/profile/password/verify-token',
    ACCOUNT_REFRESH: '/account/me?connectionInfo=true&refresh=true',
    CLASSIFICATION: '/allocations/asset-classifications?filter=:filter',
    ACCOUNT_SUBTYPE: '/account/account-subtype?accountType=:accountType',
    ACCOUNT_CONNECTION_INFO: '/account/me?connectionInfo=true&refresh=false',
    ACCOUNT_DETAILS: '/account/:id?connectionInfo=true&baseCurrency=:baseCurrency',
    ACCOUNTS_WITH_PROVIDER: '/account/me?baseCurrency=true&connectionInfo=true&refresh=false',
    HOLDINGS_ACCOUNTS_BY_DESCRIPTION: '/account-details/holdings/accounts?description=:description',
    FORM_FIELD_FILTER: '/account/form-fields-filter?accountType=:accountType&accountSubType=:accountSubType',
  },
  subscription: {
    CURRENT_SUB: '/subscription/me',
    SUB: '/subscription/stripe/subscriptions',
    STRIPE_CHECKOUT: '/subscription/stripe/checkout',
    CANCEL: '/subscription/me/cancel',
  },
  yodlee: {
    FAST_LINK: '/account/yodlee/fastlink',
    FAST_LINK_UPDATE: '/account/yodlee/fastlink?update=:update&refresh=:refresh&accountId=:accountId',
  },
  networth: {
    NETWORTH: '/networth',
  },
  allocations: {
    ALLOCATIONS: '/allocations',
    CHART_SETTINGS: '/allocations/me/chart-settings',
    UPLOAD_CHART: '/allocations/upload-chart',
    HOLDING_TYPES: '/allocations/holding-types',
  },
  account: {
    BALANCES: '/account-details/balances',
    BALANCE_ACCOUNT: '/account-details/balances/account/:accountId',
  },
};
