export const websiteRouteConstant = {
  DEF: '/w',
  HOME: '/w/home',
  TERMS: '/w/terms',
  ABOUT: '/w/about',
  LOGIN: '/w/login',
  NOT_FOUND: '/w/404',
  NOTICE: '/w/notice',
  PRIVACY: '/w/privacy',
  PRICING: '/w/pricing',
  SECURITY: '/w/security',
  EXPIRED_LINK: '/w/expired-link',
  FORGOT_PASSWORD: '/w/forgot-password',
  CREATE_NEW_PASSWORD: '/w/create-new-password',
  SUBSCRIPTION_ENDED: '/w/subscription-ended-one',
  LOGIN_SESSION_EXPIRED: '/w/login-session-expired',
  SUBSCRIPTION_ENDED_TWO: '/w/subscription-ended-two',
  SUBSCRIPTION_ENDED_THREE: '/w/subscription-ended-three',
  FEATURES_NET_WORTH: '/w/features-net-worth',
};
